
# mysql con


spring:
    datasource:
        url: jdbc:mysql://localhost:3306/school-management-system?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: 
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
            show-sql: true
