
# mysql con


spring:
  application:
      name: university-manager
  sql:
    init:
      data-locations: classpath:/sql/data.sql
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop